---
- name: Analysis
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true

  vars:
    rhsm_username: MY_USERNAME
    rhsm_password: MY_PASSWORD
    rhsm_org: MY_ORG
    rhsm_activation_key: MY_ACTIVATION_KEY

  roles:
    - role: configure-dns

    - role: update-system

    - role: oracle-linux-specific
      when: ansible_facts['distribution'] == "OracleLinux"

  tasks:
    - name: Check resolv.conf
      ansible.builtin.command: cat /etc/resolv.conf

    - name: Generate pre-conversion analysis report
      ansible.builtin.import_role:
        name: infra.convert2rhel.analysis
