---
- name: Convert
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  tasks:
    - name: Perform OS conversion
      ansible.builtin.import_role:
        name: infra.convert2rhel.convert
