---
- hosts: all
  tasks:
    - name: Check if resolv.conf file exists
      ansible.builtin.stat:
        path: /etc/resolv.conf
      register: file_info

    - name: Create /etc/resolv.conf if it exists
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: touch
      when: not file_info.stat.exists

    - name: Set DNS nameservers in /etc/resolv.conf
      ansible.builtin.blockinfile:
        path: /etc/resolv.conf
        block: |
            search example.com
            nameserver 8.8.8.8
            nameserver 8.8.4.4
