---
- name: Convert
  hosts: all
  strategy: free
  become: true
  force_handlers: true

  vars:
    convert_convert2rhel_opts: "--auto-attach"
    rhsm_activation_key: ""
    rhsm_org: ""

  roles:
    - role: configure-dns

  tasks:
    - name: Perform OS conversion
      ansible.builtin.import_role:
        name: infra.convert2rhel.convert
