---
- name: Prepare to convert major version 7
  hosts: all
  become: true

  vars:
    rhsm_username: ""
    rhsm_password: ""

  tasks:
    - name: Check if resolv.conf file exists
      ansible.builtin.stat:
        path: /etc/resolv.conf
      register: file_info

    - name: Create /etc/resolv.conf if it exists
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: touch
      when: not file_info.stat.exists

    - name: Set DNS nameservers in /etc/resolv.conf
      ansible.builtin.blockinfile:
        path: /etc/resolv.conf
        block: |
            nameserver 8.8.8.8
            nameserver 8.8.4.4

    - name: Download the signing keys
      ansible.builtin.get_url:
        url: http://www.redhat.com/security/data/fd431d51.txt
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

    - name: Make sure destination dir exists
      ansible.builtin.file:
        path: /etc/rhsm/ca
        state: directory

    - name: Copy the SSL certificates from Red Hat Subscription Management
      ansible.builtin.get_url:
        url: https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem
        dest: /etc/rhsm/ca/redhat-uep.pem

    - name: Add PEM certificate to chain 
      ansible.builtin.shell: openssl x509 -noout -hash -in /etc/rhsm/ca/redhat-uep.pem 


# https://dnf.readthedocs.io/en/latest/conf_ref.html
# DNF by default uses the global configuration file at /etc/dnf/dnf.conf and all *.repo files found under /etc/yum.repos.d. The latter is typically used for repository configuration and takes precedence over global configuration.    
    
    - name: Download a repository definition
      ansible.builtin.get_url:
        url: https://ftp.redhat.com/redhat/convert2rhel/7/convert2rhel.repo
        dest: /etc/yum.repos.d/convert2rhel.repo

    - name: Add repository
      ansible.builtin.yum_repository:
        name: convert2rhel
        description: convert2rhel repository
        baseurl: https://cdn-public.redhat.com/content/public/addon/dist/convert2rhel/server/7/7Server/x86_64/os/
        skip_if_unavailable: true 
      notify: 
        - clean yum
      
    - name: Upgrade and install main dependencies via yum all packages
      ansible.builtin.yum:
        name: 
        - '*'
        - yum-utils
        - "@Development tools"
        state: latest
        exclude: dnf*, dnf-utils, python3-six, python3-dbus, python3-pexpect, zabbix*
        lock_timeout: 300
        sslverify: false
        skip_broken: true
      ignore_errors: true
      notify: 
        - clean yum

    - name: clean yum
      ansible.builtin.shell: yum clean all
      ignore_errors: true

    - name: Install Convert2RHEL
      ansible.builtin.yum:
        name: convert2rhel
        state: present
        exclude: dnf*, dnf-utils, python3-six, python3-dbus, python3-pexpect
        skip_broken: true
        sslverify: false

    - name: Clean duplicates set default kernel
      ansible.builtin.shell: | 
        package-cleanup -y --cleandupes
        yum-complete-transaction --cleanup-only
        grubby --set-default /boot/vmlinuz-`rpm -q --qf "%{BUILDTIME}\t%{EVR}.%{ARCH}\n" kernel | sort -nr | head -1 | cut -f2`

    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 600
      register: back_again
      ignore_errors: true

    - name: Wait additional 10 minutes and try to reconnect (in case of previous task timeout/connection issue)
      ansible.builtin.wait_for_connection:
        timeout: 300
        # when reboot is successful "changed" is true
      register: back_again2
      when: not back_again.changed
      ignore_errors: true

#    - name: Wait additional 5 minutes as last resort (really slow env)
#      ansible.builtin.wait_for_connection:
#        timeout: 300
#      when: not back_again2.changed
#      register: back_again3

    - name: Add convert2rhel.ini file
      ansible.builtin.template:
        src: convert2rhel.ini.j2
        dest: /tmp/convert2rhel.ini
        mode: 0600

    - name: Run convert2RHEL for 7 major version
      ansible.builtin.shell: convert2rhel -y --config-file=/tmp/convert2rhel.ini --auto-attach
      environment:
        CONVERT2RHEL_UNSUPPORTED_INCOMPLETE_ROLLBACK: 1

  handlers:
    - name: clean yum
      ansible.builtin.shell: yum clean all
      ignore_errors: true