---
- name: Prepare to convert major version 7
  hosts: all
  strategy: free
  become: true

  roles:
    - role: configure-dns

  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Download the signing keys
      ansible.builtin.get_url:
        url: https://www.redhat.com/security/data/fd431d51.txt
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

    - name: Make sure destination dir exists
      file:
        path: /etc/rhsm/ca
        state: directory

    - name: Copy the SSL certificates from Red Hat Subscription Management
      ansible.builtin.get_url:
        url: https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem
        dest: /etc/rhsm/ca/redhat-uep.pem

    - name: Download a repository definition
      ansible.builtin.get_url:
        url: https://ftp.redhat.com/redhat/convert2rhel/7/convert2rhel.repo
        dest: /etc/yum.repos.d/convert2rhel.repo

    - name: Install Convert2RHEL
      ansible.builtin.yum:
        name: kernel-3.10.0-1160.114.2.0.1.el7
        state: present

    - name: Set default kernel
      ansible.builtin.shell: grubby --set-default /boot/vmlinuz-`rpm -q --qf "%{BUILDTIME}\t%{EVR}.%{ARCH}\n" kernel | sort -nr | head -1 | cut -f2`

   - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 900
      register: back_again
      ignore_errors: yes
      register: back_again
      ignore_errors: yes

    - name: Wait additional 10 minutes and try to reconnect (in case of previous task timeout/connection issue)
      ansible.builtin.wait_for_connection:
        timeout: 600
      # when reboot is successful "changed" is true
      register: back_again2
      when: not back_again.changed
      ignore_errors: yes

    - name: Wait additional 5 minutes as last resort (really slow env)
      ansible.builtin.wait_for_connection:
        timeout: 300
      when: not back_again2.changed
      register: back_again3
