---
- name: Reboot
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true

  tasks:
    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 900
      register: back_again
      ignore_errors: yes

    - name: Wait additional 10 minutes and try to reconnect (in case of previous task timeout/connection issue)
      ansible.builtin.wait_for_connection:
        timeout: 600
      # when reboot is successful "changed" is true
      register: back_again2
      when: not back_again.changed
      ignore_errors: yes

    - name: Wait additional 5 minutes as last resort (really slow env)
      ansible.builtin.wait_for_connection:
        timeout: 300
      when: not back_again2.changed
      register: back_again3
