---
- name: Prepare to convert major version 8
  hosts: all
  become: true

  vars:
    rhsm_username: ""
    rhsm_password: ""

  tasks:
    - name: Download the signing keys
    ansible.builtin.get_url:
      url: https://www.redhat.com/security/data/fd431d51.txt
      dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

  - name: Make sure destination dir exists
    file:
      path: /etc/rhsm/ca
      state: directory

  - name: Copy the SSL certificates from Red Hat Subscription Management
    ansible.builtin.get_url:
      url: https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem
      dest: /etc/rhsm/ca/redhat-uep.pem